services:
  mariadb:
    build: ./mariadb
    image: mariadb
    container_name: mariadb
    env_file:
     - .env
    volumes:
     - mariadb_data:/var/lib/mysql
    networks:
     - inception
    restart: always

  wordpress:
    build: ./wordpress
    image: wordpress
    container_name: wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always

  nginx:
    build:
      context: ./nginx
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always
  
networks:
  inception:
    name: inception

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/andcarva/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/andcarva/data/wordpress
